spring.application.name=ridelink

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ridelink?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
# Base64-encoded 512-bit HMAC key
ridelink.jwt.secret=9a6563c2246b281f62cf1b4df0df68c5b05872a95c80ef497cbb11a3d002f1f6d3a8220c3290610a56247c40562e84d43486c91e2b58832a83271cc43cf76a8d
ridelink.jwt.access-token-expiration-ms=900000
ridelink.jwt.refresh-token-expiration-ms=604800000
